// Debug script to check your redirect URI construction
const siteUrl = "https://accountconnections.vly.site"; // Your actual SITE_URL

const redirectUri = new URL("/", siteUrl).toString();
console.log("Generated redirect URI:", redirectUri);
console.log("Your LinkedIn app should have this EXACT URL:", redirectUri);
console.log("");
console.log("Current LinkedIn setting: https://accountconnections.vly.site/");
console.log("Generated by your code:", redirectUri);
console.log("Match?", redirectUri === "https://accountconnections.vly.site/" ? "✅ YES" : "❌ NO");

// Additional checks
console.log("");
console.log("=== Additional Checks ===");
console.log("URL without trailing slash:", siteUrl);
console.log("URL with trailing slash:", redirectUri);
console.log("");
console.log("If LinkedIn has 'https://accountconnections.vly.site' (no slash), that's your problem!");
console.log("If LinkedIn has 'https://accountconnections.vly.site/' (with slash), that should work.");
