// Debug script to check your redirect URI construction
const siteUrl = "https://main.d165ycqnmbuafx.amplifyapp.com"; // Your actual SITE_URL

const redirectUri = new URL("/linkedin-callback", siteUrl).toString();
console.log("Generated redirect URI:", redirectUri);
console.log("Your LinkedIn app should have this EXACT URL:", redirectUri);
console.log("");
console.log("Current LinkedIn setting: [CHECK YOUR LINKEDIN APP]");
console.log("Generated by your code:", redirectUri);
console.log("Expected format:", "https://main.d165ycqnmbuafx.amplifyapp.com/linkedin-callback");
console.log("Match?", redirectUri === "https://main.d165ycqnmbuafx.amplifyapp.com/linkedin-callback" ? "✅ YES" : "❌ NO");

// Additional checks
console.log("");
console.log("=== Additional Checks ===");
console.log("URL without trailing slash:", siteUrl);
console.log("URL with trailing slash:", redirectUri);
console.log("");
console.log("If LinkedIn has 'https://main.d165ycqnmbuafx.amplifyapp.com' (no slash), that's your problem!");
console.log("If LinkedIn has 'https://main.d165ycqnmbuafx.amplifyapp.com/' (with slash), that should work.");
